version: '3'
services:
  traefik:
    ports:
      - 443:443
    volumes:
      - ./config/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./config/traefik/ssl.toml:/etc/traefik/ssl.toml
      - ./config/traefik/config:/config

  keycloak:
    labels:
      - 'traefik.http.routers.keycloak.rule=Host(`$APP_DOMAIN`) && PathPrefix(`/auth`)'
      - 'traefik.http.routers.keycloak.tls=true'
      - 'traefik.http.routers.keycloak.tls.certresolver=le'

  loki:
    labels:
      - 'traefik.http.routers.loki.rule=Host(`$APP_DOMAIN`) && PathPrefix(`/loki`)'
      - 'traefik.http.routers.loki.tls=true'
      - 'traefik.http.routers.loki.tls.certresolver=le'

  pylon:
    labels:
      - 'traefik.http.routers.pylon.rule=Host(`$APP_DOMAIN`) && PathPrefix(`/`)'
      - 'traefik.http.routers.pylon.tls=true'
      - 'traefik.http.routers.pylon.tls.certresolver=le'

  pylon_auth:
    environment:
      - CORE_CONFIG_SEED=file:/data/config/pylon_auth_ssl.yml
    labels:
      - 'traefik.http.routers.pylon-auth.rule=Host(`$APP_DOMAIN`) && PathPrefix(`/forward-auth`)'
      - 'traefik.http.routers.pylon-auth.tls=true'
      - 'traefik.http.routers.pylon-auth.tls.certresolver=le'
