# Intended to be used together with the base docker-compose.yaml file for cases when a custom CA cert is needed for the system.
# CUSTOM_CA_CERT env var must be set.
# See an example usage at Makefile -> up_with_custom_CA_cert.

version: '3'
services:
  pylon:
    environment:
      SSL_CERT_FILE: /etc/ssl/certs/custom-ca-cert.pem
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/custom-ca-cert.pem
      CURL_CA_BUNDLE: /etc/ssl/certs/custom-ca-cert.pem
    volumes:
      - $CUSTOM_CA_CERT:/etc/ssl/certs/custom-ca-cert.pem:ro
  pylon_auth:
    environment:
      SSL_CERT_FILE: /etc/ssl/certs/custom-ca-cert.pem
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/custom-ca-cert.pem
      CURL_CA_BUNDLE: /etc/ssl/certs/custom-ca-cert.pem
    volumes:
      - $CUSTOM_CA_CERT:/etc/ssl/certs/custom-ca-cert.pem:ro
  traefik:
    volumes:
      - $CUSTOM_CA_CERT:/etc/ssl/certs/custom-ca-cert.pem:ro
  influx:
    volumes:
      - $CUSTOM_CA_CERT:/etc/ssl/certs/custom-ca-cert.pem:ro
  minio:
    environment:
      MINIO_SERVER_CA_CERTS_FILE: /etc/ssl/certs/custom-ca-cert.pem
    volumes:
      - $CUSTOM_CA_CERT:/etc/ssl/certs/custom-ca-cert.pem:ro
  interceptor:
    environment:
      SSL_CERT_FILE: /etc/ssl/certs/custom-ca-cert.pem
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/custom-ca-cert.pem
      CURL_CA_BUNDLE: /etc/ssl/certs/custom-ca-cert.pem
    volumes:
      - $CUSTOM_CA_CERT:/etc/ssl/certs/custom-ca-cert.pem:ro
  interceptor_internal:
    environment:
      SSL_CERT_FILE: /etc/ssl/certs/custom-ca-cert.pem
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/custom-ca-cert.pem
      CURL_CA_BUNDLE: /etc/ssl/certs/custom-ca-cert.pem
    volumes:
      - $CUSTOM_CA_CERT:/etc/ssl/certs/custom-ca-cert.pem:ro
